# Generated by Django 5.0.2 on 2024-02-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('question_slug', models.SlugField()),
                ('attempt_error', models.TextField()),
                ('attempt_output', models.TextField()),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
