# Generated by Django 5.0.2 on 2024-02-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_codeattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeattempt',
            name='languge_user',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
